/**
 * Coviu Session API
 * Coviu provides a session based API for creating and restricting access to coviu calls. The core concepts exposed are* Session: A coviu call that occurs between two or more parties at a specified time, and has a finite duration.* Participants: Users who may participate in a coviu call.Participants join a call by following a session link in their browser, or mobile app. The session link identifiesthe participant, including their name, optional avatar, and importantly their role. As such, it is important thateach person joining the call be issued a different session link, i.e. have a distinct participant created for them.A participant's role identifies whether that user may access the call directly, or if they are required the be let inby an existing participant.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.coviu.sessions.model;

import java.util.Objects;
import com.coviu.sessions.model.ParticipantCreationRequest;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;


/**
 * SessionCreationRequest
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-15T11:45:03.343+11:00")
public class SessionCreationRequest   {
  @SerializedName("feature_flags")
  private List<String> featureFlags = new ArrayList<String>();

  @SerializedName("participants")
  private List<ParticipantCreationRequest> participants = new ArrayList<ParticipantCreationRequest>();

  @SerializedName("picture")
  private String picture = null;

  @SerializedName("start_time")
  private DateTime startTime = null;

  @SerializedName("end_time")
  private DateTime endTime = null;

  @SerializedName("session_name")
  private String sessionName = null;

  public SessionCreationRequest featureFlags(List<String> featureFlags) {
    this.featureFlags = featureFlags;
    return this;
  }

  public SessionCreationRequest addFeatureFlagsItem(String featureFlagsItem) {
    this.featureFlags.add(featureFlagsItem);
    return this;
  }

   /**
   * Get featureFlags
   * @return featureFlags
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getFeatureFlags() {
    return featureFlags;
  }

  public void setFeatureFlags(List<String> featureFlags) {
    this.featureFlags = featureFlags;
  }

  public SessionCreationRequest participants(List<ParticipantCreationRequest> participants) {
    this.participants = participants;
    return this;
  }

  public SessionCreationRequest addParticipantsItem(ParticipantCreationRequest participantsItem) {
    this.participants.add(participantsItem);
    return this;
  }

   /**
   * Get participants
   * @return participants
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<ParticipantCreationRequest> getParticipants() {
    return participants;
  }

  public void setParticipants(List<ParticipantCreationRequest> participants) {
    this.participants = participants;
  }

  public SessionCreationRequest picture(String picture) {
    this.picture = picture;
    return this;
  }

   /**
   * Get picture
   * @return picture
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPicture() {
    return picture;
  }

  public void setPicture(String picture) {
    this.picture = picture;
  }

  public SessionCreationRequest startTime(DateTime startTime) {
    this.startTime = startTime;
    return this;
  }

   /**
   * Get startTime
   * @return startTime
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public DateTime getStartTime() {
    return startTime;
  }

  public void setStartTime(DateTime startTime) {
    this.startTime = startTime;
  }

  public SessionCreationRequest endTime(DateTime endTime) {
    this.endTime = endTime;
    return this;
  }

   /**
   * Get endTime
   * @return endTime
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public DateTime getEndTime() {
    return endTime;
  }

  public void setEndTime(DateTime endTime) {
    this.endTime = endTime;
  }

  public SessionCreationRequest sessionName(String sessionName) {
    this.sessionName = sessionName;
    return this;
  }

   /**
   * Get sessionName
   * @return sessionName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSessionName() {
    return sessionName;
  }

  public void setSessionName(String sessionName) {
    this.sessionName = sessionName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SessionCreationRequest sessionCreationRequest = (SessionCreationRequest) o;
    return Objects.equals(this.featureFlags, sessionCreationRequest.featureFlags) &&
        Objects.equals(this.participants, sessionCreationRequest.participants) &&
        Objects.equals(this.picture, sessionCreationRequest.picture) &&
        Objects.equals(this.startTime, sessionCreationRequest.startTime) &&
        Objects.equals(this.endTime, sessionCreationRequest.endTime) &&
        Objects.equals(this.sessionName, sessionCreationRequest.sessionName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(featureFlags, participants, picture, startTime, endTime, sessionName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SessionCreationRequest {\n");
    
    sb.append("    featureFlags: ").append(toIndentedString(featureFlags)).append("\n");
    sb.append("    participants: ").append(toIndentedString(participants)).append("\n");
    sb.append("    picture: ").append(toIndentedString(picture)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    sessionName: ").append(toIndentedString(sessionName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

