/**
 * Coviu Session API
 * Coviu provides a session based API for creating and restricting access to coviu calls. The core concepts exposed are* Session: A coviu call that occurs between two or more parties at a specified time, and has a finite duration.* Participants: Users who may participate in a coviu call.Participants join a call by following a session link in their browser, or mobile app. The session link identifiesthe participant, including their name, optional avatar, and importantly their role. As such, it is important thateach person joining the call be issued a different session link, i.e. have a distinct participant created for them.A participant's role identifies whether that user may access the call directly, or if they are required the be let inby an existing participant.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.coviu.sessions.model;

import java.util.Objects;
import com.coviu.sessions.model.Participant;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;


/**
 * Session
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-15T10:12:43.225+11:00")
public class Session   {
  @SerializedName("feature_flags")
  private List<String> featureFlags = new ArrayList<String>();

  @SerializedName("session_id")
  private String sessionId = null;

  @SerializedName("team_id")
  private String teamId = null;

  @SerializedName("client_id")
  private String clientId = null;

  @SerializedName("participants")
  private List<Participant> participants = new ArrayList<Participant>();

  @SerializedName("picture")
  private String picture = null;

  @SerializedName("start_time")
  private DateTime startTime = null;

  @SerializedName("end_time")
  private DateTime endTime = null;

  @SerializedName("canceled_time")
  private String canceledTime = null;

  @SerializedName("session_name")
  private String sessionName = null;

  public Session featureFlags(List<String> featureFlags) {
    this.featureFlags = featureFlags;
    return this;
  }

  public Session addFeatureFlagsItem(String featureFlagsItem) {
    this.featureFlags.add(featureFlagsItem);
    return this;
  }

   /**
   * Get featureFlags
   * @return featureFlags
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getFeatureFlags() {
    return featureFlags;
  }

  public void setFeatureFlags(List<String> featureFlags) {
    this.featureFlags = featureFlags;
  }

  public Session sessionId(String sessionId) {
    this.sessionId = sessionId;
    return this;
  }

   /**
   * Get sessionId
   * @return sessionId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSessionId() {
    return sessionId;
  }

  public void setSessionId(String sessionId) {
    this.sessionId = sessionId;
  }

  public Session teamId(String teamId) {
    this.teamId = teamId;
    return this;
  }

   /**
   * Get teamId
   * @return teamId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTeamId() {
    return teamId;
  }

  public void setTeamId(String teamId) {
    this.teamId = teamId;
  }

  public Session clientId(String clientId) {
    this.clientId = clientId;
    return this;
  }

   /**
   * Get clientId
   * @return clientId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getClientId() {
    return clientId;
  }

  public void setClientId(String clientId) {
    this.clientId = clientId;
  }

  public Session participants(List<Participant> participants) {
    this.participants = participants;
    return this;
  }

  public Session addParticipantsItem(Participant participantsItem) {
    this.participants.add(participantsItem);
    return this;
  }

   /**
   * Get participants
   * @return participants
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Participant> getParticipants() {
    return participants;
  }

  public void setParticipants(List<Participant> participants) {
    this.participants = participants;
  }

  public Session picture(String picture) {
    this.picture = picture;
    return this;
  }

   /**
   * Get picture
   * @return picture
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPicture() {
    return picture;
  }

  public void setPicture(String picture) {
    this.picture = picture;
  }

  public Session startTime(DateTime startTime) {
    this.startTime = startTime;
    return this;
  }

   /**
   * Get startTime
   * @return startTime
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public DateTime getStartTime() {
    return startTime;
  }

  public void setStartTime(DateTime startTime) {
    this.startTime = startTime;
  }

  public Session endTime(DateTime endTime) {
    this.endTime = endTime;
    return this;
  }

   /**
   * Get endTime
   * @return endTime
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public DateTime getEndTime() {
    return endTime;
  }

  public void setEndTime(DateTime endTime) {
    this.endTime = endTime;
  }

  public Session canceledTime(String canceledTime) {
    this.canceledTime = canceledTime;
    return this;
  }

   /**
   * Get canceledTime
   * @return canceledTime
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCanceledTime() {
    return canceledTime;
  }

  public void setCanceledTime(String canceledTime) {
    this.canceledTime = canceledTime;
  }

  public Session sessionName(String sessionName) {
    this.sessionName = sessionName;
    return this;
  }

   /**
   * Get sessionName
   * @return sessionName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSessionName() {
    return sessionName;
  }

  public void setSessionName(String sessionName) {
    this.sessionName = sessionName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Session session = (Session) o;
    return Objects.equals(this.featureFlags, session.featureFlags) &&
        Objects.equals(this.sessionId, session.sessionId) &&
        Objects.equals(this.teamId, session.teamId) &&
        Objects.equals(this.clientId, session.clientId) &&
        Objects.equals(this.participants, session.participants) &&
        Objects.equals(this.picture, session.picture) &&
        Objects.equals(this.startTime, session.startTime) &&
        Objects.equals(this.endTime, session.endTime) &&
        Objects.equals(this.canceledTime, session.canceledTime) &&
        Objects.equals(this.sessionName, session.sessionName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(featureFlags, sessionId, teamId, clientId, participants, picture, startTime, endTime, canceledTime, sessionName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Session {\n");
    
    sb.append("    featureFlags: ").append(toIndentedString(featureFlags)).append("\n");
    sb.append("    sessionId: ").append(toIndentedString(sessionId)).append("\n");
    sb.append("    teamId: ").append(toIndentedString(teamId)).append("\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    participants: ").append(toIndentedString(participants)).append("\n");
    sb.append("    picture: ").append(toIndentedString(picture)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    canceledTime: ").append(toIndentedString(canceledTime)).append("\n");
    sb.append("    sessionName: ").append(toIndentedString(sessionName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

